Make login script actually work

diff --git a/shared/files/agent/montagu-docker-login b/shared/files/agent/montagu-docker-login
--- a/shared/files/agent/montagu-docker-login
+++ b/shared/files/agent/montagu-docker-login
@@ -6,7 +6,17 @@ if [ -z $VAULT_AUTH_GITHUB_TOKEN ]; then
 fi
 export VAULT_AUTH_GITHUB_TOKEN
 
+set -e
+vault auth -method=github > /dev/null
+
+REGISTRY_URL=docker.montagu.dide.ic.ac.uk:5000
 REGISTRY_USER=vimc
 REGISTRY_PASSWORD=$(vault read -field=password /secret/registry/${REGISTRY_USER})
-REGISTRY_URL=docker.montagu.dide.ic.ac.uk:5001
-docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY_URL
+
+if [ -z $REGISTRY_PASSWORD ]; then
+    echo "Failed to fetch password from vault"
+    exit 1
+fi
+
+echo $REGISTRY_PASSWORD | \
+    docker login -u $REGISTRY_USER --password-stdin $REGISTRY_URL
