use new password for hub

diff --git a/shared/files/agent/montagu-docker-login b/shared/files/agent/montagu-docker-login
--- a/shared/files/agent/montagu-docker-login
+++ b/shared/files/agent/montagu-docker-login
@@ -11,16 +11,22 @@ vault auth -method=github > /dev/null
 
 REGISTRY_URL=docker.montagu.dide.ic.ac.uk:5000
 REGISTRY_USER=vimc
-HUB_USER=vimcrobot
 REGISTRY_PASSWORD=$(vault read -field=password /secret/registry/${REGISTRY_USER})
 
+HUB_USER=vimcrobot
+HUB_PASSWORD=$(vault read -field=password /secret/${HUB_USER$)
 if [ -z $REGISTRY_PASSWORD ]; then
-    echo "Failed to fetch password from vault"
+    echo "Failed to fetch registry password from vault"
+    exit 1
+fi
+
+if [ -z $HUB_PASSWORD ]; then
+    echo "Failed to fetch hub password from vault"
     exit 1
 fi
 
 echo $REGISTRY_PASSWORD | \
     docker login -u $REGISTRY_USER --password-stdin $REGISTRY_URL
 
-echo $REGISTRY_PASSWORD | \
+echo $HUB_PASSWORD | \
     docker login -u $HUB_USER --password-stdin
